name: Check points of contact for users

on:
  push:
    paths:
      - 'users.nix'
  pull_request_target:
    paths:
      - 'users.nix'
  workflow_dispatch:

jobs:
  check:
    name: Run check

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26

      - name: Evaluate checks
        run: |
          nix eval --show-trace --file checks/check-contacts.nix
